-- noinspection SqlNoDataSourceInspectionForFile
-- Application DB table schemas in SQL format

CREATE TABLE hotel
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name 				TEXT NOT NULL,
    city 				TEXT NOT NULL,
    state				TEXT NOT NULL,
    zip					INT NOT NULL CHECK (zip BETWEEN 500 AND 99999),
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE room
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id 			INT NOT NULL,
    num_rooms 			INT NOT NULL,
    num_beds			INT NOT NULL,
    floor				INT NOT NULL,
    is_reservable_flag	INT NOT NULL CHECK (is_paid_flag IN (0, 1)),
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(hotel_id) REFERENCES hotel(id)
);

CREATE TABLE guest
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name 			TEXT NOT NULL,
    last_name 			TEXT NOT NULL,
    address				TEXT NOT NULL,
    phone				INT NOT NULL,
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reservation
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id 			INT NOT NULL,
    room_id 			INT NOT NULL,
    rate_id				INT NOT NULL,
    discount_pct		INT NOT NULL,
    start_date			TEXT NOT NULL CHECK (start_date IS date(start_date)),
    end_date			TEXT NOT NULL CHECK (end_date IS date(end_date)),
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(guest_id) REFERENCES guest(id),
    FOREIGN KEY(room_id) REFERENCES room(id),
    FOREIGN KEY(rate_id) REFERENCES rate(id)
);

CREATE TABLE rate
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_type 			TEXT NOT NULL,
    rate_amount			INT NOT NULL,
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice
(
    id    				INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id 			INT NOT NULL,
    reservation_id		INT NOT NULL,
    amount				INT NOT NULL,
    is_paid_flag		INT NOT NULL CHECK (is_paid_flag IN (0, 1)),
    date_paid			TEXT,
    create_timestamp	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(guest_id) REFERENCES guest(id),
    FOREIGN KEY(reservation_id) REFERENCES reservation(id)
);


-- Seed data for DB tables in SQL format

-- Insert sample records into the `hotel` table
INSERT INTO hotel (name, city, state, zip) VALUES
('Grand Plaza', 'New York', 'NY', 10001),
('Ocean View', 'Miami', 'FL', 33101),
('Mountain Retreat', 'Denver', 'CO', 80201);

-- Insert sample records into the `room` table
INSERT INTO room (hotel_id, num_rooms, num_beds, floor, is_reservable_flag) VALUES
(1, 1, 2, 1, 1),
(1, 1, 1, 1, 1),
(2, 2, 3, 2, 0);

-- Insert sample records into the `guest` table
INSERT INTO guest (first_name, last_name, address, phone) VALUES
('John', 'Doe', '123 Elm St, New York, NY', 1234567890),
('Jane', 'Smith', '456 Oak St, Miami, FL', 9876543210),
('Alice', 'Johnson', '789 Pine St, Denver, CO', 5551234567);

-- Insert sample records into the `rate` table
INSERT INTO rate (rate_type, rate_amount) VALUES
('Elite', 150),
('Preferred', 250),
('Standard', 400);

-- Insert sample records into the `reservation` table
INSERT INTO reservation (guest_id, room_id, rate_id, discount_pct, start_date, end_date) VALUES
(1, 1, 1, 10, '2023-10-01', '2023-10-05'),
(2, 2, 2, 0, '2023-10-10', '2023-10-15'),
(3, 3, 3, 5, '2023-10-20', '2023-10-25');

-- Insert sample records into the `invoice` table
INSERT INTO invoice (guest_id, reservation_id, amount, is_paid_flag, date_paid) VALUES
(1, 1, 135, 1, '2023-10-06'),
(2, 2, 250, 0, NULL),
(3, 3, 380, 1, '2023-10-26');
